#!/usr/bin/env python3
"""
VisualizeImpact.py  —  IEEE-quality result figures for Q-V Droop FDI simulation
═══════════════════════════════════════════════════════════════════════════════
Reads outputs from  VectorDataset_Droop_AC_Q/  (generated by SimulateIsland_Q.m)
and produces four publication-ready figures:

  Fig 1 — BDD Stealthiness Validation
  Fig 2 — Attack Injection vs. Real Voltage Impact (precision analysis)
  Fig 3 — Voltage Stability Degradation (distribution + timeline)
  Fig 4 — Operational Impact: Load Shedding Analysis

BUGS FIXED vs. previous version
  1. Directory path corrected: VectorDataset_Droop_AC_Q  (was _Reactive)
  2. Fig 2 sign error fixed: scatter now plots |ΔV_min| (positive) on y-axis
     vs designed injection ΔV_inj (positive) on x-axis.
     Previously: delta_V_real (negative) vs volt_design (positive)
     → scatter in 4th quadrant while y=x reference was in 1st quadrant.
  3. Inf values in bdd_tau_log handled gracefully (replaced with NaN before
     any division/log operations).
  4. Full IEEE formatting: Times New Roman, 300 DPI, double-column widths.
  5. Figures saved as both .png (journals) and .pdf (LaTeX inclusion).

Run from the directory that contains VectorDataset_Droop_AC_Q/.
"""

import os
import sys
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from scipy import stats
from collections import Counter

# ── IEEE-compatible matplotlib settings ──────────────────────────────────────
matplotlib.rcParams.update({
    'font.family'       : 'serif',
    'font.serif'        : ['Times New Roman', 'Times', 'DejaVu Serif'],
    'font.size'         : 10,
    'axes.labelsize'    : 10,
    'axes.titlesize'    : 10,
    'xtick.labelsize'   : 9,
    'ytick.labelsize'   : 9,
    'legend.fontsize'   : 9,
    'legend.framealpha' : 0.85,
    'lines.linewidth'   : 1.0,
    'axes.linewidth'    : 0.8,
    'xtick.major.width' : 0.8,
    'ytick.major.width' : 0.8,
    'figure.dpi'        : 150,   # screen preview
    'savefig.dpi'       : 300,   # saved files
})

# ── Paths ─────────────────────────────────────────────────────────────────────
DATA_DIR   = r'C:\Users\abide\Downloads\FDI_Microgrid_Project (2)\FDI_Microgrid_Project\FDI_Microgrid_Project\MATLAB\VectorDataset_Droop_AC_Q'
OUTPUT_DIR = r'C:\Users\abide\Downloads\FDI_Microgrid_Project (2)\FDI_Microgrid_Project\FDI_Microgrid_Project\MATLAB\VectorDataset_Droop_AC_Q'

# IEEE figure widths (inches)
PAGE_W = 7.16   # double-column (full width)
COL_W  = 3.50   # single-column

# Print-safe colour palette (distinguishable in greyscale with line styles)
C_ATT  = '#C0392B'   # crimson    — attack
C_NOM  = '#27AE60'   # green      — normal
C_TAU  = '#2980B9'   # blue       — detection threshold
C_UVLS = '#E67E22'   # orange     — UVLS threshold
C_FIT  = '#8E44AD'   # purple     — regression / fit


# ── Utility ───────────────────────────────────────────────────────────────────
def load_csv(fname, dtype=float):
    """Load a single-column CSV; exit with a clear message if missing."""
    path = os.path.join(DATA_DIR, fname)
    if not os.path.exists(path):
        sys.exit(
            f"\n[ERROR] Missing file: {path}\n"
            f"        Please run SimulateIsland_Q.m first to generate the dataset.\n"
        )
    return pd.read_csv(path, header=None)[0].values.astype(dtype)


def despine(ax):
    """Remove top and right spines for a cleaner academic look."""
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)


def save_fig(name):
    """Save figure as both PNG (300 dpi) and PDF for LaTeX."""
    for ext in ('png', 'pdf'):
        plt.savefig(os.path.join(OUTPUT_DIR, f'{name}.{ext}'), bbox_inches='tight')
    print(f"  ✓ {name}.{{png,pdf}}")
    plt.close()


# ── Load all CSV outputs ──────────────────────────────────────────────────────
print(f"\nLoading data from: {DATA_DIR}/")

J_attack     = load_csv('J_attack.csv')
J_true       = load_csv('J_true.csv')
bdd_tau_raw  = load_csv('bdd_tau.csv')
labels       = load_csv('labelData.csv', dtype=int)
delta_V_real = load_csv('delta_V_real.csv')    # signed: V_min - V_nom [p.u.]
volt_design  = load_csv('voltDeviations.csv')  # injection magnitude   [p.u.]
bdd_res      = load_csv('bddResults.csv', dtype=int)

# Non-stealthy baseline (only populated for attack steps)
J_naive_all     = None
naive_det_all   = None
try:
    J_naive_all   = load_csv('J_naive.csv')
    naive_det_all = load_csv('naive_detected.csv', dtype=int)
except SystemExit:
    print("  Note: J_naive.csv not found — Fig 5 will be skipped.")
    print("        Re-run SimulateIsland_Q.m to generate it.\n")

ls_events = None
ls_path = os.path.join(DATA_DIR, 'ls_events.csv')
if os.path.exists(ls_path):
    ls_events = pd.read_csv(ls_path, header=None)[0].values

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── Derived masks ─────────────────────────────────────────────────────────────
attack_mask = (labels == 1)
normal_mask = (labels == 0)
idx         = np.arange(len(labels))
n_total     = len(labels)
n_att       = int(attack_mask.sum())
n_nom       = int(normal_mask.sum())

print(f"  Total steps  : {n_total}")
print(f"  Attack steps : {n_att}  ({100*n_att/n_total:.1f}%)")
print(f"  Normal steps : {n_nom}  ({100*n_nom/n_total:.1f}%)")

# ── BDD threshold: replace Inf / non-positive with NaN ───────────────────────
# FIX: previous code did semilogy(bdd_tau) directly; Inf crashes the log scale.
tau = bdd_tau_raw.copy().astype(float)
tau[np.isinf(tau) | (tau <= 0)] = np.nan

# Normalised residuals J / tau
with np.errstate(invalid='ignore', divide='ignore'):
    J_att_norm = np.where(~np.isnan(tau), J_attack / tau, np.nan)
    J_tr_norm  = np.where(~np.isnan(tau), J_true   / tau, np.nan)

print(f"\nGenerating IEEE figures in: {OUTPUT_DIR}/")


# ═════════════════════════════════════════════════════════════════════════════
# FIGURE 1 — BDD Stealthiness Validation
# ─────────────────────────────────────────────────────────────────────────────
# (a) Time-series of normalised WLS residuals over the simulation horizon.
#     Key result: J_att / tau ≈ J_true / tau < 1 at all steps.
#                 The attack evades BDD by construction.
# (b) Box-plot comparison: residual distributions under normal vs. attack.
# ═════════════════════════════════════════════════════════════════════════════
fig, axes = plt.subplots(1, 2, figsize=(PAGE_W, 2.8))
fig.subplots_adjust(wspace=0.38)

# (a) time-series
ax = axes[0]
ax.plot(idx[normal_mask], J_tr_norm[normal_mask],
        color=C_NOM, lw=0.5, alpha=0.75, zorder=2,
        label=r'Normal ($J_{true}/\tau$)')
ax.scatter(idx[attack_mask], J_att_norm[attack_mask],
           c=C_ATT, s=5, alpha=0.7, edgecolors='none', zorder=3,
           label=r'FDI attack ($J_{att}/\tau$)')
ax.axhline(1.0, color=C_TAU, ls='--', lw=1.0, zorder=4,
           label='Detection limit ($J/\\tau = 1$)')

valid_norm = J_tr_norm[normal_mask & ~np.isnan(J_tr_norm)]
valid_att  = J_att_norm[attack_mask & ~np.isnan(J_att_norm)]
y_top = max(1.6,
            (np.nanmax(valid_att)  * 1.15 if len(valid_att)  else 1.6),
            (np.nanmax(valid_norm) * 1.15 if len(valid_norm) else 1.6))
ax.set_xlim([0, n_total])
ax.set_ylim([0, y_top])
ax.set_xlabel('Simulation Step')
ax.set_ylabel(r'Normalised WLS Residual $J/\tau$')
ax.set_title('(a) WLS Residual Evolution')
ax.legend(loc='upper right', markerscale=2.5, handlelength=1.5)
ax.grid(True, alpha=0.2, lw=0.4)
despine(ax)

# (b) box-plot
ax2 = axes[1]
valid_nom_bp  = valid_norm[np.isfinite(valid_norm)]
valid_att_bp  = valid_att [np.isfinite(valid_att)]
bp = ax2.boxplot([valid_nom_bp, valid_att_bp],
                 patch_artist=True,
                 medianprops=dict(color='black', lw=1.5),
                 whiskerprops=dict(lw=0.8),
                 capprops=dict(lw=0.8),
                 flierprops=dict(marker='.', ms=2, alpha=0.35))
bp['boxes'][0].set(facecolor=C_NOM, alpha=0.65)
bp['boxes'][1].set(facecolor=C_ATT, alpha=0.65)
ax2.set_xticklabels(['Normal\nOperation', 'FDI\nAttack'])
ax2.axhline(1.0, color=C_TAU, ls='--', lw=1.0, label='Detection limit')
ax2.set_ylabel(r'Normalised WLS Residual $J/\tau$')
ax2.set_title('(b) Residual Distribution Comparison')
ax2.legend(loc='upper right')
ax2.grid(True, alpha=0.2, axis='y', lw=0.4)
despine(ax2)

save_fig('Fig1_BDD_Stealthiness')


# ═════════════════════════════════════════════════════════════════════════════
# FIGURE 2 — Attack Precision: Injection vs. System Voltage Impact
# ─────────────────────────────────────────────────────────────────────────────
# FIX: y-axis is now |delta_V_real| (positive voltage DROP magnitude)
#      Previously: delta_V_real (negative) plotted against positive x-axis
#      → scatter sat in quadrant IV while y=x reference was in quadrant I.
#
# (a) Scatter: designed injection ΔV_inj vs. actual |ΔV_min|.
#     y=x reference: ideal 1:1 coupling between injection and system response.
#     Linear fit + R² quantifies how predictable the attack effect is.
# (b) Amplification factor |ΔV_min| / ΔV_inj distribution.
# ═════════════════════════════════════════════════════════════════════════════
valid_att_mask = attack_mask & ~np.isnan(delta_V_real)
x_inj     = volt_design[valid_att_mask]          # designed injection [p.u.]  (+)
y_drop    = np.abs(delta_V_real[valid_att_mask])  # actual voltage drop [p.u.] (+)

fig, axes = plt.subplots(1, 2, figsize=(PAGE_W, 2.8))
fig.subplots_adjust(wspace=0.38)

ax = axes[0]
ax.scatter(x_inj, y_drop, c=C_ATT, s=10, alpha=0.45, edgecolors='none',
           label='Attack instance')

# 1:1 reference (perfect injection-to-impact coupling)
ref_lim = [0.03, 0.13]
ax.plot(ref_lim, ref_lim, 'k--', lw=1.0,
        label=r'Ideal 1:1 coupling ($|\Delta V_{min}| = \Delta V_{inj}$)')

# Linear regression
if len(x_inj) >= 4:
    slope, intercept, r_val, _, _ = stats.linregress(x_inj, y_drop)
    x_fit = np.linspace(x_inj.min(), x_inj.max(), 100)
    ax.plot(x_fit, slope*x_fit + intercept, color=C_FIT, lw=1.0,
            label=f'Linear fit ($R^2={r_val**2:.3f}$)')

ax.set_xlabel(r'Injected False Voltage Offset $\Delta V_{inj}$ (p.u.)')
ax.set_ylabel(r'Min. Bus Voltage Drop $|\Delta V_{min}|$ (p.u.)')
ax.set_title('(a) Attack Injection vs. System Impact')
ax.legend(loc='upper left', fontsize=8)
ax.grid(True, alpha=0.2, lw=0.4)
despine(ax)

ax2 = axes[1]
if len(x_inj) >= 4:
    amp = y_drop / x_inj
    amp = amp[np.isfinite(amp) & (amp > 0)]
    ax2.hist(amp, bins=28, color=C_ATT, alpha=0.70, density=True, edgecolor='none')
    med = float(np.median(amp))
    ax2.axvline(med, color='black', ls='--', lw=1.0,
                label=f'Median = {med:.3f}')
    ax2.set_xlabel(r'Impact Amplification $|\Delta V_{min}| / \Delta V_{inj}$')
    ax2.set_ylabel('Probability Density')
    ax2.set_title('(b) Amplification Factor Distribution')
    ax2.legend(fontsize=9)
    ax2.grid(True, alpha=0.2, lw=0.4)
    despine(ax2)

save_fig('Fig2_Attack_Precision')


# ═════════════════════════════════════════════════════════════════════════════
# FIGURE 3 — Voltage Stability Degradation
# ─────────────────────────────────────────────────────────────────────────────
# (a) Overlapping histograms of ΔV_min under normal vs. attack conditions.
#     UVLS threshold at −0.10 p.u. and OVLS at +0.10 p.u.
# (b) Timeline of ΔV_min: attack instants marked as scatter points on top of
#     the continuous normal-operation trace.
# ═════════════════════════════════════════════════════════════════════════════
dv_att_vals = delta_V_real[attack_mask & ~np.isnan(delta_V_real)]
dv_nom_vals = delta_V_real[normal_mask & ~np.isnan(delta_V_real)]

fig, axes = plt.subplots(1, 2, figsize=(PAGE_W, 2.8))
fig.subplots_adjust(wspace=0.38)

ax = axes[0]
all_dv = np.concatenate([dv_att_vals, dv_nom_vals])
margin = 0.005
bins   = np.linspace(all_dv.min() - margin, all_dv.max() + margin, 45)
ax.hist(dv_nom_vals, bins=bins, color=C_NOM, alpha=0.65,
        density=True, edgecolor='none', label='Normal operation')
ax.hist(dv_att_vals, bins=bins, color=C_ATT, alpha=0.65,
        density=True, edgecolor='none', label='Under FDI attack')
ax.axvline(-0.10, color=C_UVLS, ls='--', lw=1.0,
           label='UVLS threshold (−0.10 p.u.)')
ax.axvline( 0.10, color='#8E44AD', ls=':', lw=1.0,
           label='OVLS threshold (+0.10 p.u.)')
ax.set_xlabel(r'Min. Bus Voltage Deviation $\Delta V_{min}$ (p.u.)')
ax.set_ylabel('Probability Density')
ax.set_title('(a) Voltage Deviation Distribution')
ax.legend(fontsize=8)
ax.grid(True, alpha=0.2, lw=0.4)
despine(ax)

ax2 = axes[1]
ax2.plot(idx[normal_mask], delta_V_real[normal_mask],
         color=C_NOM, lw=0.5, alpha=0.80, zorder=2, label='Normal')
ax2.scatter(idx[attack_mask], delta_V_real[attack_mask],
            c=C_ATT, s=5, alpha=0.70, edgecolors='none', zorder=3, label='Attack')
ax2.axhline(-0.10, color=C_UVLS, ls='--', lw=1.0, label='UVLS (−0.10 p.u.)')
ax2.set_xlim([0, n_total])
ax2.set_xlabel('Simulation Step')
ax2.set_ylabel(r'$\Delta V_{min}$ (p.u.)')
ax2.set_title('(b) Voltage Deviation Timeline')
ax2.legend(fontsize=8, markerscale=2.5)
ax2.grid(True, alpha=0.2, lw=0.4)
despine(ax2)

save_fig('Fig3_Voltage_Stability')


# ═════════════════════════════════════════════════════════════════════════════
# FIGURE 4 — Operational Impact: Load Shedding Analysis
# ─────────────────────────────────────────────────────────────────────────────
# (a) Grouped bar chart — event counts under normal vs. attack.
# (b) Pie chart — proportion of attack outcomes
#     (Stable / UVLS / OVLS / Convergence failure).
# ═════════════════════════════════════════════════════════════════════════════
if ls_events is not None:
    ls_att = ls_events[attack_mask]
    ls_nom = ls_events[normal_mask]

    cats     = ['None', 'UVLS', 'OVLS', 'Fail']
    att_cnts = Counter(ls_att)
    nom_cnts = Counter(ls_nom)
    att_vals = [att_cnts.get(c, 0) for c in cats]
    nom_vals = [nom_cnts.get(c, 0) for c in cats]

    fig, axes = plt.subplots(1, 2, figsize=(PAGE_W, 2.8))
    fig.subplots_adjust(wspace=0.45)

    # (a) grouped bar chart
    ax = axes[0]
    x = np.arange(len(cats))
    w = 0.35
    b1 = ax.bar(x - w/2, nom_vals, w, label='Normal',
                color=C_NOM, alpha=0.70, edgecolor='none')
    b2 = ax.bar(x + w/2, att_vals, w, label='Attack',
                color=C_ATT, alpha=0.70, edgecolor='none')
    # Annotate attack bar counts
    for bar, val in zip(b2, att_vals):
        if val > 0:
            ax.text(bar.get_x() + bar.get_width()/2,
                    bar.get_height() + max(att_vals)*0.01,
                    str(val), ha='center', va='bottom', fontsize=8)
    ax.set_xticks(x)
    ax.set_xticklabels(cats)
    ax.set_ylabel('Event Count')
    ax.set_title('(a) Protection Event Frequency')
    ax.legend()
    ax.grid(True, alpha=0.2, axis='y', lw=0.4)
    despine(ax)

    # (b) pie chart of attack outcomes
    ax2 = axes[1]
    labels_pie  = [c for c, v in zip(cats, att_vals) if v > 0]
    vals_pie    = [v for v in att_vals if v > 0]
    colors_pie  = [C_ATT if c in ('UVLS','OVLS','Fail') else C_NOM
                   for c in labels_pie]
    if vals_pie:
        wedges, texts, autotexts = ax2.pie(
            vals_pie, labels=labels_pie, colors=colors_pie,
            autopct='%1.1f%%', startangle=90,
            wedgeprops={'linewidth': 0.5, 'edgecolor': 'white'},
            textprops={'fontsize': 9}
        )
        for at in autotexts:
            at.set_fontsize(8)
    ax2.set_title(f'(b) Attack Outcome Breakdown\n($n_{{att}}={n_att}$)')

    save_fig('Fig4_Load_Shedding')
else:
    print("  ✗ Fig4 skipped — ls_events.csv not found.")


# ═════════════════════════════════════════════════════════════════════════════
# FIGURE 5 — FDI vs. Non-Stealthy Baseline: BDD Detection Comparison
# ─────────────────────────────────────────────────────────────────────────────
# This is the key discriminative figure for the paper.
# Both attacks inject a perturbation of IDENTICAL L2 norm into the measurement
# vector z. The FDI attack uses z_a = z + H*c (in col(H) → invisible to BDD).
# The naive attack injects the same-norm random Gaussian noise (not in col(H)).
#
# Expected result:
#   J_fdi  ≈ J_true  << tau   (stealthy — BDD cannot distinguish from normal)
#   J_naive >> tau             (detected — BDD flags every naive injection)
#
# (a) Scatter: J_fdi vs J_naive for all attack steps, with tau lines.
# (b) Bar chart: detection rates — FDI evades BDD while naive is always caught.
# ═════════════════════════════════════════════════════════════════════════════
if J_naive_all is not None and naive_det_all is not None:

    J_fdi_att   = J_attack[attack_mask]       # FDI residual at attack steps
    J_naive_att = J_naive_all                  # naive residual (attack steps only)
    tau_att     = tau[attack_mask]             # threshold at attack steps
    fdi_pct     = 100 * bdd_res[attack_mask].mean()
    naive_pct   = 100 * naive_det_all.mean()

    fig, axes = plt.subplots(1, 2, figsize=(PAGE_W, 2.8))
    fig.subplots_adjust(wspace=0.38)

    # (a) scatter: J_fdi vs J_naive, per-step tau as colour reference
    ax = axes[0]
    valid = ~np.isnan(tau_att)
    J_fdi_norm   = np.where(valid, J_fdi_att   / tau_att, np.nan)
    J_naive_norm = np.where(valid, J_naive_att / tau_att, np.nan)

    ax.scatter(J_naive_norm[valid], J_fdi_norm[valid],
               c=C_ATT, s=8, alpha=0.45, edgecolors='none',
               label='Attack step (FDI vs. Naive)')
    ax.axhline(1.0, color=C_TAU, ls='--', lw=1.0, label='Detection limit $J/\\tau=1$')
    ax.axvline(1.0, color=C_TAU, ls='--', lw=1.0)

    # Annotate quadrants
    xlim = ax.get_xlim(); ylim = ax.get_ylim()
    ax.set_xlim([0, max(xlim[1], np.nanmax(J_naive_norm[valid])*1.05)])
    ax.set_ylim([0, max(ylim[1], np.nanmax(J_fdi_norm[valid])*1.15)])
    xr = ax.get_xlim(); yr = ax.get_ylim()
    ax.text(xr[0]*0.05 + xr[1]*0.55, yr[1]*0.08,
            'FDI stealthy\nNaive detected', color='#555', fontsize=7.5,
            ha='left', style='italic')
    ax.text(xr[0]*0.05 + xr[1]*0.02, yr[1]*0.08,
            'Both stealthy\n(rare)', color='#555', fontsize=7.5,
            ha='left', style='italic')

    ax.set_xlabel(r'Naive residual $J_{naive}/\tau$')
    ax.set_ylabel(r'FDI residual $J_{fdi}/\tau$')
    ax.set_title('(a) Residual Comparison: FDI vs. Naive Attack')
    ax.legend(loc='upper left', fontsize=8, markerscale=2)
    ax.grid(True, alpha=0.2, lw=0.4)
    despine(ax)

    # (b) grouped detection-rate bar chart
    ax2 = axes[1]
    categories = ['FDI Attack\n(H·c construction)', 'Naive Attack\n(random noise)']
    evade_pct  = [fdi_pct,           100 - naive_pct]  # % that EVADE BDD
    detect_pct = [100 - fdi_pct,     naive_pct]         # % that BDD CATCHES

    x = np.arange(len(categories))
    w = 0.40
    b1 = ax2.bar(x, evade_pct,  w, label='Evades BDD (stealthy)', color=C_ATT, alpha=0.70)
    b2 = ax2.bar(x, detect_pct, w, label='Detected by BDD',       color=C_NOM, alpha=0.70,
                 bottom=evade_pct)

    for bar, val in zip(b1, evade_pct):
        ax2.text(bar.get_x() + bar.get_width()/2, val/2,
                 f'{val:.1f}%', ha='center', va='center',
                 fontsize=9, color='white', fontweight='bold')
    for bar, v_bot, val in zip(b2, evade_pct, detect_pct):
        if val > 1:
            ax2.text(bar.get_x() + bar.get_width()/2, v_bot + val/2,
                     f'{val:.1f}%', ha='center', va='center',
                     fontsize=9, color='white', fontweight='bold')

    ax2.set_xticks(x)
    ax2.set_xticklabels(categories, fontsize=9)
    ax2.set_ylim([0, 110])
    ax2.set_ylabel('Percentage of Attack Steps (%)')
    ax2.set_title('(b) BDD Detection Rate Comparison')
    ax2.legend(loc='upper right', fontsize=8)
    ax2.grid(True, alpha=0.2, axis='y', lw=0.4)
    despine(ax2)

    save_fig('Fig5_FDI_vs_Naive_BDD')
    print(f"     FDI stealthy rate : {fdi_pct:.1f}%")
    print(f"     Naive caught rate : {naive_pct:.1f}%")
else:
    print("  ✗ Fig5 skipped — J_naive.csv / naive_detected.csv not found.")


# ── Summary statistics ────────────────────────────────────────────────────────
tau_valid = tau[~np.isnan(tau)]
print()
print("=" * 52)
print("  REACTIVE FDI SIMULATION — SUMMARY")
print("=" * 52)
if len(tau_valid):
    print(f"BDD threshold tau (final) : {tau_valid[-1]:.4f}")
if n_att > 0:
    dv_r = delta_V_real[attack_mask & ~np.isnan(delta_V_real)]
    br   = bdd_res[attack_mask]
    print(f"Stealthy FDI attacks      : {int(br.sum())}/{n_att}  ({100*br.mean():.1f}%)")
    if J_naive_all is not None:
        nd   = naive_det_all
        print(f"Naive attacks detected    : {int(nd.sum())}/{n_att}  ({100*nd.mean():.1f}%)")
        print(f"BDD evasion advantage     : {100*br.mean() - 100*(1-nd.mean()):.1f} pp")
    print(f"Mean injection dV_inj     : +{volt_design[attack_mask].mean():.4f} p.u.")
    print(f"Mean |DV_min| (real)      :  {np.abs(dv_r).mean():.4f} p.u.")
    if ls_events is not None:
        ls_a = ls_events[attack_mask]
        uvls_n = int((ls_a == 'UVLS').sum())
        print(f"UVLS events               :  {uvls_n}  ({100*uvls_n/n_att:.1f}%)")
print("=" * 52)
print(f"Figures saved to: {OUTPUT_DIR}/\n")